---
- name: Configure OPS445 CentOS 7 VM
  hosts: vmlab
  user: student
  become: yes
  vars:
    seneca_id: kppatel43  # <-- Replace this with your real Seneca ID
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    base_dir: "/home/{{ seneca_id }}/ops445"

  tasks:
    - name: Update Apache (httpd) to latest version
      yum:
        name: httpd
        state: latest

    - name: Ensure EPEL repository is installed
      yum:
        name: epel-release
        state: present

    - name: Remove tree package if installed
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create a new user with sudo access
      user:
        name: "{{ seneca_id }}"
        state: present
        groups: wheel
        shell: /bin/bash
        create_home: yes

    - name: Add SSH public key to new user
      authorized_key:
        user: "{{ seneca_id }}"
        key: "{{ ssh_pub_key }}"
        state: present

    - name: Create ops445 lab directory structure
      file:
        path: "{{ base_dir }}/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ range(1,9)|list }}"

